# Page settings

baseURL = "https://resume-demo.bas.work/"
languageCode = "en"
title = "YG Herve"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Yves-Guillaume HERVE"
    description = "Après mes années en tant que chef de projet, je veux revenir vers la technique. Je suis en pleine montée en compétences des outils nécessaires pour le poste de DevOps. Mon passé professionnel est un plus pour appréhender les enjeux et les contraintes de tout le processus de création d’un logiciel."
    og_image = "better-software.png"
    ghRepo = "https://github.com/Ysadsir/codewithbas_resume"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true
        name = "Yves-Guillaume HERVE"
        tagline = "DevOps"
        avatar = "photo.png"

    [params.contact]
        enable = true

        location = "France"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:+33671174861"
        text = "+33671174861"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:yg.herve@gmail.com"
        text = "yg.herve@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://linktr.ee/ygherve"
        text = "My links on the web"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "IaC"
        text = "Terraform"


        [[params.skills.list]]
        title = "Professionelles"
        text = "Ouverture d’esprit"

        
    [params.education]
        enable = true

        [[params.education.list]]
        degree = "DUT GEA"
        university = "IUT – VANNES"
        dates = "1993-1995"

        [[params.education.list]]
        degree = "Informatique de gestion"
        university = "AFPA – CRETEIL"
        dates = "1998-1999"

        [[params.education.list]]
        degree = "Administrateur Système DevOps"
        university = "LA CAPSULE"
        dates = "2023"

    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Certified System Admin (LFCS)"
        body = "LINUX FOUDATION"
        date = "2023"

        [[params.awards.list]]
        name = "Certified Kubernetes Admin (CKA)"
        body = "CNCF"
        date = "2023"

    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Read"

        [[params.languages.list]]
        name = "French"
        level = "Fluent"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Roller"


    [params.summary]
        enable = true
        text = "Après mes années en tant que chef de projet, je veux revenir vers la technique. Je suis en pleine montée en compétences des outils nécessaires pour le poste de DevOps. Mon passé professionnel est un plus pour appréhender les enjeux et les contraintes de tout le processus de création d’un logiciel."


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "DevOps"
        dates = "2023"
        company = "La Capsule"
        details = "Déploiement d’un site de consultation de news"
        [[params.experience.list.items]]
        details = "Mettre en place l’infra, la CI / CD, la sécurité, le monitoring, le backup de base de données"
        details = "Logiciels : Terraform, Ansible, K8s, Docker, AWS, Gitlab, Jest, Locust, SonarQube, Fail2ban, Let’s Encrypt, Prometheus, Grafana, Bash, Crongold, MongoDB"

        [[params.experience.list]]
        title = "Chef de projet informatique"
        dates = "2017 – 2023"
        company = "B-appli Studio"
        details = "ERP en mode Saas"
        [[params.experience.list.items]]
        details = "Gérer des équipes (10 à 15 personnes), animer les échanges client Indexia Group (Assurance affinitaire), gérer le suivi des projets"
        details = "Logiciels : PHP, Redmine"

        [[params.experience.list]]
        title = "Développeur logiciel / Chef de projet informatique"
        dates = "2006 – 2017"
        company = "ITGA"
        details = "Progiciel de gestion de diagnostics immobiliers"
        [[params.experience.list.items]]
        details = "Gérer une équipe (3 à 5 personnes), animer les échanges client, gérer le suivi du projet"
        details = "Logiciels : C#, SQL Azure DevOps Server"

        [[params.experience.list]]
        title = "Développeur logiciel"
        dates = "1999 – 2006"
        company = "SODIFRANCE"
        [[params.experience.list.items]]
        details = "Tesson informatique : progiciel de gestion de magasins non alimentaires (VB6, SQL Server)"
        details = "Yves Rocher : Gestion de panélistes (VB.net, SQL Server)"
        details = "Equant : TMA SATIN (gestion de prise de commande) (asp.net, Oracle)"



    [params.projects]
        enable = false

        [[params.projects.list]]
        title = "This Resume"
        meta = "GitHub project"
        url = "https://github.com/codewithbas/resume"
        tagline = "A resume with a free PDF generator"


    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Cooking, Beekeeping, Cycling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/Ysadsir"
        title = "/ysadsir"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://www.linkedin.com/in/yves-guillaume-herve/"
        title = "/in/ygherve"


